name: Build and Release macOS App

on:
  release:
    types: [created] # Trigger workflow when a new release is created

jobs:
  build:
    permissions: write-all
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            architecture: arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Install dependencies
        run: brew install hdf5

      - name: Resolve Swift Packages
        run: xcodebuild -resolvePackageDependencies -project DotTHzQL.xcodeproj

      - name: Build macOS app for ${{ matrix.target }}
        run: |
          xcodebuild -resolvePackageDependencies -project DotTHzQL.xcodeproj
          xcodebuild clean build \
          -scheme DotTHzQL \
          -configuration Release \
          -destination "platform=macOS,arch=${{ matrix.architecture }}" \
          -derivedDataPath ./build \
          | tee build.log

      - name: Package the .app into a .zip file
        run: |
          cd build/Build/Products/Release/
          zip -r DotTHzQL-${{ matrix.target }}.app.zip DotTHzQL.app
          mv DotTHzQL-${{ matrix.target }}.app.zip $GITHUB_WORKSPACE/
          
      - name: Package the .app into a .zip file
        run: |
          cd build/Build/Products/Release/
          zip -r DotTHzQLExtension-${{ matrix.target }}.appex.zip DotTHzQLExtension.appex
          mv DotTHzQLExtension-${{ matrix.target }}.appex.zip $GITHUB_WORKSPACE/
          
      - name: Upload .zip of .app
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: DotTHzQL-${{ matrix.target }}.app.zip
          asset_name: DotTHzQL-${{ matrix.target }}.app.zip
          asset_content_type: application/zip
      
      - name: Upload .zip of .appex
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: DotTHzQLExtension-${{ matrix.target }}.appex.zip
          asset_name: DotTHzQLExtension-${{ matrix.target }}.appex.zip
          asset_content_type: application/zip
